image: ubuntu/bionic

packages:
    - python
    - python-pip
    - python3
    - python3-pip

secrets:
    - d622464e-897f-41d3-ba3e-99999999999

sources:
    - https://github.com/flywire/caption

tasks:
    - setup: |
        pip3 install setuptools wheel twine virtualenv

    - tests: |
        # Access the virtualenv binary
        export PATH=$PATH:~/.local/bin

        # Begin tests
        cd caption

        virtualenv -p python2 venv
        . venv/bin/activate
        pip install -r requirements.txt
        python -m unittest discover
        deactivate
        rm -rf venv

        virtualenv -p python3 venv
        . venv/bin/activate
        pip install -r requirements.txt
        python -m unittest discover
        deactivate
        rm -rf venv

    - deploy: |
        cd caption
        if [ "$(git tag --points-at HEAD)" == "$(grep version setup.py | sed 's/.*\"\(.*\)\",/v\1/')" ]; then
            python3 setup.py sdist bdist_wheel --universal
            python3 -m twine upload --config-file ~/.pypirc dist/*
        fi

triggers:
    - action: email
      condition: failure
      to: "flywire <flywire0@gmail.com>"
